# specfile generated by rpmerizor (http://sourceforge.net/projects/rpmerizor/)

# if you are using __spec_only and want to build rpm package
# after, from command line, you have to use the following syntaxe
# rpmbuild -bb --buildroot=/tmp/rpmerizor_buildroot your_specfile.spec

# supported algorithm (cf rpmsign)
# may be SHA1, SHA256, SHA384, and SHA512
# represented as 2, 8, 9, and 10 respectively
# use 1 for md5 for compatibility with rpm < 4.6.0
# %global _binary_filedigest_algorithm 1
# %global _source_filedigest_algorithm 1

%define defaultbuildroot /
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0

%define name    llvm-21-python3-local
%define version 21.1.1

Summary: The LLVM Compiler Infrastructure.
Name: %{name}
Version: %{version}
Release: 300.fc41
License: Apache 2.0 With LLVM Exception
Group: C and C++ Development Tools and Libraries
BuildArch: x86_64
URL: https://llvm.org/
Packager: Stefan Teleman <stefan.teleman@ieee.org>
# autoreq and autoprov
AutoReqProv: yes

%description
Python 3.13 Bindings for LLVM. The LLVM Project is a collection of modular and reusable compiler and toolchain technologies. Despite its name, LLVM has little to do with traditional virtual machines. The name 'LLVM' itself is not an acronym; it is the full name of the project.

%prep
ln -s /src/steleman/programming/llvm-21.1.1/install-llvm-python3 /tmp/rpmerizor_buildroot

%clean
rm /tmp/rpmerizor_buildroot

%files
%dir /usr/local/lib64/python3.13/site-packages
%dir /usr/local/lib64/python3.13/site-packages/lldb
%dir /usr/local/lib64/python3.13/site-packages/lldb/formatters
%dir /usr/local/lib64/python3.13/site-packages/lldb/formatters/cpp
%dir /usr/local/lib64/python3.13/site-packages/lldb/plugins
%dir /usr/local/lib64/python3.13/site-packages/lldb/utils
/usr/local/lib64/python3.13/site-packages/lldb/_lldb.cpython-313-x86_64-linux-gnu.so
/usr/local/lib64/python3.13/site-packages/lldb/lldb-argdumper
/usr/local/lib64/python3.13/site-packages/lldb/__init__.py
/usr/local/lib64/python3.13/site-packages/lldb/embedded_interpreter.py
/usr/local/lib64/python3.13/site-packages/lldb/formatters/Logger.py
/usr/local/lib64/python3.13/site-packages/lldb/formatters/__init__.py
/usr/local/lib64/python3.13/site-packages/lldb/formatters/attrib_fromdict.py
/usr/local/lib64/python3.13/site-packages/lldb/formatters/cache.py
/usr/local/lib64/python3.13/site-packages/lldb/formatters/cpp/__init__.py
/usr/local/lib64/python3.13/site-packages/lldb/formatters/cpp/gnu_libstdcpp.py
/usr/local/lib64/python3.13/site-packages/lldb/formatters/cpp/libcxx.py
/usr/local/lib64/python3.13/site-packages/lldb/formatters/metrics.py
/usr/local/lib64/python3.13/site-packages/lldb/formatters/synth.py
/usr/local/lib64/python3.13/site-packages/lldb/plugins/__init__.py
/usr/local/lib64/python3.13/site-packages/lldb/plugins/operating_system.py
/usr/local/lib64/python3.13/site-packages/lldb/plugins/parsed_cmd.py
/usr/local/lib64/python3.13/site-packages/lldb/plugins/scripted_platform.py
/usr/local/lib64/python3.13/site-packages/lldb/plugins/scripted_process.py
/usr/local/lib64/python3.13/site-packages/lldb/plugins/scripted_thread_plan.py
/usr/local/lib64/python3.13/site-packages/lldb/utils/__init__.py
/usr/local/lib64/python3.13/site-packages/lldb/utils/in_call_stack.py
/usr/local/lib64/python3.13/site-packages/lldb/utils/symbolication.py

